In [1]:
import requests
import config, json
from iex import IEXStock
from helpers import format_number
from datetime import datetime, timedelta
import pandas as pd

In [2]:
pd.options.display.max_columns = None

In [3]:
print(config.IEX_TOKEN)

pk_a90d9f537768487cb94c0a569b623440

In [4]:
stock = IEXStock(config.IEX_TOKEN, 'AAPL', environment='production')
print(stock)

<iex.IEXStock object at 0x7f493c6c0b50>

In [5]:
stock.BASE_URL

'https://cloud.iexapis.com/v1'

In [6]:
logo = stock.get_logo()
print(logo)

{'url': 'https://storage.googleapis.com/iexcloud-hl37opg/api/logos/AAPL.png'}

In [7]:
import requests

In [29]:
def get_stats():
        url = f"https://sandbox.iexapis.com/v1/stock/MSFT/advanced-stats?token=Tpk_0d86b559558d4860a55abf3f4ff857f8"
        print(url)
        r = requests.get(url)
        
        return r.json()

In [30]:
a = get_stats()
a

https://sandbox.iexapis.com/v1/stock/MSFT/advanced-stats?token=Tpk_0d86b559558d4860a55abf3f4ff857f8

{'beta': 1.310166311274971,
 'totalCash': 131516531465,
 'currentDebt': 88662194292,
 'revenue': 169176593543,
 'grossProfit': 121024860783,
 'totalRevenue': 174549892003,
 'EBITDA': 81869372702,
 'revenuePerShare': 22.77,
 'revenuePerEmployee': 1036082.29,
 'debtToEquity': 2.4085725601083725,
 'profitMargin': 0.37298515926099496,
 'enterpriseValue': 2140897901291,
 'enterpriseValueToRevenue': 12.44,
 'priceToSales': 13.41,
 'priceToBook': 15.3,
 'forwardPERatio': 0.0016820445113033865,
 'pegRatio': 0.91200081401631,
 'peHigh': 47.74875164308784,
 'peLow': 31.961281578145137,
 'week52highDate': '2021-07-22',
 'week52lowDate': '2020-09-08',
 'putCallRatio': 1.0024155417694274,
 'companyName': 'Microsoft Corporation',
 'marketcap': 2249461053418,
 'week52high': 300.99,
 'week52low': 203.57,
 'week52highSplitAdjustOnly': 296.39,
 'week52highDateSplitAdjustOnly': '2021-07-24',
 'week52lowSplitAdjustOnly': 197.44,
 'week52lowDateSplitAdjustOnly': '2020-09-07',
 'week52change': 0.37684012058155,
 'sharesOutstanding': 7870643855,
 'float': None,
 'avg10Volume': 24008013,
 'avg30Volume': 25419591,
 'day200MovingAvg': 252.38,
 'day50MovingAvg': 278.22,
 'employees': 170176,
 'ttmEPS': 8.38,
 'ttmDividendRate': 2.1937890371729853,
 'dividendYield': 0.007750688350775135,
 'nextDividendDate': '2021-08-13',
 'exDividendDate': '',
 'nextEarningsDate': '2021-10-16',
 'peRatio': 35.694698237217,
 'maxChangePercent': 11.419021261198735,
 'year5ChangePercent': 4.588086477096253,
 'year2ChangePercent': 1.160736192507987,
 'year1ChangePercent': 0.3405356195720737,
 'ytdChangePercent': 0.3087252047878488,
 'month6ChangePercent': 0.1876927904883699,
 'month3ChangePercent': 0.1436823271288065,
 'month1ChangePercent': 0.03487764963891942,
 'day30ChangePercent': 0.03545600942588343,
 'day5ChangePercent': 0.002100956523599735}

In [22]:
a

In [8]:
stats = stock.get_stats()

print(stats)

https://cloud.iexapis.com/v1/stock/AAPL/advanced-stats?token=pk_a90d9f537768487cb94c0a569b623440
{'beta': 1.5168896530347769, 'totalCash': 61696000000, 'currentDebt': 107754000000, 'revenue': 347155000000, 'grossProfit': 142351000000, 'totalRevenue': 347155000000, 'EBITDA': 110935000000, 'revenuePerShare': 21, 'revenuePerEmployee': 2361598.64, 'debtToEquity': 5.131300560049782, 'profitMargin': 0.25003816738920653, 'enterpriseValue': 2479450095760, 'enterpriseValueToRevenue': 7.14, 'priceToSales': 6.97, 'priceToBook': 37.64, 'forwardPERatio': 3.494045998317244, 'pegRatio': 0.5085530493418565, 'peHigh': 13.549325302357351, 'peLow': 10.145067071770969, 'week52highDate': '2021-08-17', 'week52lowDate': '2020-09-21', 'putCallRatio': 0.4238904328809243, 'companyName': 'Apple Inc', 'marketcap': 2419355095760, 'week52high': 151.68, 'week52low': 102.44, 'week52highSplitAdjustOnly': 151.68, 'week52highDateSplitAdjustOnly': '2021-08-17', 'week52lowSplitAdjustOnly': 103.1, 'week52lowDateSplitAdjustOnly': '2020-09-21', 'week52change': 0.2730498921439011, 'sharesOutstanding': 16530166000, 'float': None, 'avg10Volume': 76112168, 'avg30Volume': 72064580, 'day200MovingAvg': 132.29, 'day50MovingAvg': 145.85, 'employees': 147000, 'ttmEPS': 5.1, 'ttmDividendRate': 0.8480583982979361, 'dividendYield': 0.0057943317730113145, 'nextDividendDate': None, 'exDividendDate': '', 'nextEarningsDate': '2021-10-28', 'peRatio': 27.872112344876847, 'maxChangePercent': 55.257687576875774, 'year5ChangePercent': 4.722798525116423, 'year2ChangePercent': 1.8816072107121133, 'year1ChangePercent': 0.27464641538354373, 'ytdChangePercent': 0.10820439238431279, 'month6ChangePercent': 0.131973614094139, 'month3ChangePercent': 0.17404334238171337, 'month1ChangePercent': 0.0012930061366482892, 'day30ChangePercent': 0.02898755526871022, 'day5ChangePercent': 0.0034279446044152007}

In [9]:
type(stats)

dict

In [10]:
stats['beta']

1.5168896530347769

In [13]:
df_stats = pd.DataFrame.from_dict(stats, orient='index', columns=['values'])
# df_stats.to_excel('stats_aapl.xlsx')

In [11]:
bal_sheet= stock.get_balancesheet(last=4)

print(bal_sheet)

{'symbol': 'AAPL', 'balancesheet': [{'accountsPayable': 42296000000, 'capitalSurplus': None, 'commonStock': 17352119000, 'currency': 'USD', 'currentAssets': 143713000000, 'currentCash': 90943000000, 'currentLongTermDebt': 13769000000, 'filingType': '10-K', 'fiscalDate': '2020-09-26', 'fiscalQuarter': 0, 'fiscalYear': 2020, 'goodwill': 0, 'intangibleAssets': 0, 'inventory': 4061000000, 'longTermDebt': 98667000000, 'longTermInvestments': 180175000000, 'minorityInterest': 0, 'netTangibleAssets': 65339000000, 'otherAssets': 42522000000, 'otherCurrentAssets': 11264000000, 'otherCurrentLiabilities': 49327000000, 'otherLiabilities': 54490000000, 'propertyPlantEquipment': 36766000000, 'receivables': 37445000000, 'reportDate': '2020-10-30', 'retainedEarnings': 14966000000, 'shareholderEquity': 65339000000, 'shortTermInvestments': 11264000000, 'symbol': 'AAPL', 'totalAssets': 323888000000, 'totalCurrentLiabilities': 105392000000, 'totalLiabilities': 258549000000, 'treasuryStock': 0, 'id': 'BALANCE_SHEET', 'key': 'AAPL', 'subkey': 'annual', 'date': 1601078400000, 'updated': 1619798874000}, {'accountsPayable': 46236000000, 'capitalSurplus': None, 'commonStock': 18471336000, 'currency': 'USD', 'currentAssets': 162819000000, 'currentCash': 100557000000, 'currentLongTermDebt': 16240000000, 'filingType': '10-K', 'fiscalDate': '2019-09-28', 'fiscalQuarter': 0, 'fiscalYear': 2019, 'goodwill': 0, 'intangibleAssets': 0, 'inventory': 4106000000, 'longTermDebt': 91807000000, 'longTermInvestments': 175697000000, 'minorityInterest': 0, 'netTangibleAssets': 90488000000, 'otherAssets': 32978000000, 'otherCurrentAssets': 12352000000, 'otherCurrentLiabilities': 43242000000, 'otherLiabilities': 50503000000, 'propertyPlantEquipment': 37378000000, 'receivables': 45804000000, 'reportDate': '2019-10-31', 'retainedEarnings': 45898000000, 'shareholderEquity': 90488000000, 'shortTermInvestments': 12352000000, 'symbol': 'AAPL', 'totalAssets': 338516000000, 'totalCurrentLiabilities': 105718000000, 'totalLiabilities': 248028000000, 'treasuryStock': 0, 'id': 'BALANCE_SHEET', 'key': 'AAPL', 'subkey': 'annual', 'date': 1569628800000, 'updated': 1619798874000}, {'accountsPayable': 55888000000, 'capitalSurplus': None, 'commonStock': 19821508000, 'currency': 'USD', 'currentAssets': 131339000000, 'currentCash': 66301000000, 'currentLongTermDebt': 20748000000, 'filingType': '10-K', 'fiscalDate': '2018-09-29', 'fiscalQuarter': 0, 'fiscalYear': 2018, 'goodwill': 0, 'intangibleAssets': 0, 'inventory': 3956000000, 'longTermDebt': 93735000000, 'longTermInvestments': 234386000000, 'minorityInterest': 0, 'netTangibleAssets': 107147000000, 'otherAssets': 1983000000, 'otherCurrentAssets': 12087000000, 'otherCurrentLiabilities': 40230000000, 'otherLiabilities': 47551000000, 'propertyPlantEquipment': 41304000000, 'receivables': 48995000000, 'reportDate': '2018-11-05', 'retainedEarnings': 70400000000, 'shareholderEquity': 107147000000, 'shortTermInvestments': 12087000000, 'symbol': 'AAPL', 'totalAssets': 365725000000, 'totalCurrentLiabilities': 116866000000, 'totalLiabilities': 258578000000, 'treasuryStock': 0, 'id': 'BALANCE_SHEET', 'key': 'AAPL', 'subkey': 'annual', 'date': 1538179200000, 'updated': 1619798874000}, {'accountsPayable': 49049000000, 'capitalSurplus': None, 'commonStock': 20868968000, 'currency': 'USD', 'currentAssets': 128645000000, 'currentCash': 74181000000, 'currentLongTermDebt': 18473000000, 'filingType': '10-K', 'fiscalDate': '2017-09-30', 'fiscalQuarter': 0, 'fiscalYear': 2017, 'goodwill': 5717000000, 'intangibleAssets': 2298000000, 'inventory': 4855000000, 'longTermDebt': 97207000000, 'longTermInvestments': 246674000000, 'minorityInterest': 0, 'netTangibleAssets': 126032000000, 'otherAssets': 10162000000, 'otherCurrentAssets': 13936000000, 'otherCurrentLiabilities': 33292000000, 'otherLiabilities': 11747000000, 'propertyPlantEquipment': 33783000000, 'receivables': 35673000000, 'reportDate': '2017-11-03', 'retainedEarnings': 98330000000, 'shareholderEquity': 134047000000, 'shortTermInvestments': 13936000000, 'symbol': 'AAPL', 'totalAssets': 375319000000, 'totalCurrentLiabilities': 100814000000, 'totalLiabilities': 241272000000, 'treasuryStock': 0, 'id': 'BALANCE_SHEET', 'key': 'AAPL', 'subkey': 'annual', 'date': 1506729600000, 'updated': 1619798874000}]}

In [12]:
# Flatten data
df_nested_list = pd.json_normalize(bal_sheet, record_path =['balancesheet'])
df_nested_list

,accountsPayable,capitalSurplus,commonStock,currency,currentAssets,currentCash,currentLongTermDebt,filingType,fiscalDate,fiscalQuarter,fiscalYear,goodwill,intangibleAssets,inventory,longTermDebt,longTermInvestments,minorityInterest,netTangibleAssets,otherAssets,otherCurrentAssets,otherCurrentLiabilities,otherLiabilities,propertyPlantEquipment,receivables,reportDate,retainedEarnings,shareholderEquity,shortTermInvestments,symbol,totalAssets,totalCurrentLiabilities,totalLiabilities,treasuryStock,id,key,subkey,date,updated
0,42296000000,None,17352119000,USD,143713000000,90943000000,13769000000,10-K,2020-09-26,0,2020,0,0,4061000000,98667000000,180175000000,0,65339000000,42522000000,11264000000,49327000000,54490000000,36766000000,37445000000,2020-10-30,14966000000,65339000000,11264000000,AAPL,323888000000,105392000000,258549000000,0,BALANCE_SHEET,AAPL,annual,1601078400000,1619798874000
1,46236000000,None,18471336000,USD,162819000000,100557000000,16240000000,10-K,2019-09-28,0,2019,0,0,4106000000,91807000000,175697000000,0,90488000000,32978000000,12352000000,43242000000,50503000000,37378000000,45804000000,2019-10-31,45898000000,90488000000,12352000000,AAPL,338516000000,105718000000,248028000000,0,BALANCE_SHEET,AAPL,annual,1569628800000,1619798874000
2,55888000000,None,19821508000,USD,131339000000,66301000000,20748000000,10-K,2018-09-29,0,2018,0,0,3956000000,93735000000,234386000000,0,107147000000,1983000000,12087000000,40230000000,47551000000,41304000000,48995000000,2018-11-05,70400000000,107147000000,12087000000,AAPL,365725000000,116866000000,258578000000,0,BALANCE_SHEET,AAPL,annual,1538179200000,1619798874000
3,49049000000,None,20868968000,USD,128645000000,74181000000,18473000000,10-K,2017-09-30,0,2017,5717000000,2298000000,4855000000,97207000000,246674000000,0,126032000000,10162000000,13936000000,33292000000,11747000000,33783000000,35673000000,2017-11-03,98330000000,134047000000,13936000000,AAPL,375319000000,100814000000,241272000000,0,BALANCE_SHEET,AAPL,annual,1506729600000,1619798874000

In [17]:
# df_nested_list.to_excel('bal_sheet_aapl.xlsx')

In [20]:
cash_flow = stock.get_cash_flow(last=4)

print(cash_flow)

{'symbol': 'AAPL', 'cashflow': [{'capitalExpenditures': -7309000000, 'cashChange': -9614000000, 'cashFlow': 80674000000, 'cashFlowFinancing': -86820000000, 'changesInInventories': -45000000, 'changesInReceivables': -8359000000, 'currency': 'USD', 'depreciation': 11056000000, 'dividendsPaid': None, 'exchangeRateEffect': None, 'filingType': '10-K', 'fiscalDate': '2020-09-26', 'fiscalQuarter': 0, 'fiscalYear': 2020, 'investingActivityOther': None, 'investments': None, 'netBorrowings': 10229000000, 'netIncome': 57411000000, 'otherFinancingCashFlows': None, 'reportDate': '2020-10-30', 'symbol': 'AAPL', 'totalInvestingCashFlows': -4289000000, 'id': 'CASH_FLOW', 'key': 'AAPL', 'subkey': 'annual', 'date': 1601078400000, 'updated': 1619798873000}, {'capitalExpenditures': -10495000000, 'cashChange': 34256000000, 'cashFlow': 69391000000, 'cashFlowFinancing': -90976000000, 'changesInInventories': 150000000, 'changesInReceivables': -3191000000, 'currency': 'USD', 'depreciation': 12547000000, 'dividendsPaid': None, 'exchangeRateEffect': None, 'filingType': '10-K', 'fiscalDate': '2019-09-28', 'fiscalQuarter': 0, 'fiscalYear': 2019, 'investingActivityOther': None, 'investments': None, 'netBorrowings': -4862000000, 'netIncome': 55256000000, 'otherFinancingCashFlows': None, 'reportDate': '2019-10-31', 'symbol': 'AAPL', 'totalInvestingCashFlows': 45896000000, 'id': 'CASH_FLOW', 'key': 'AAPL', 'subkey': 'annual', 'date': 1569628800000, 'updated': 1619798873000}, {'capitalExpenditures': -13313000000, 'cashChange': -7880000000, 'cashFlow': 77434000000, 'cashFlowFinancing': -87876000000, 'changesInInventories': -899000000, 'changesInReceivables': 13322000000, 'currency': 'USD', 'depreciation': 10903000000, 'dividendsPaid': None, 'exchangeRateEffect': None, 'filingType': '10-K', 'fiscalDate': '2018-09-29', 'fiscalQuarter': 0, 'fiscalYear': 2018, 'investingActivityOther': None, 'investments': None, 'netBorrowings': 36095000000, 'netIncome': 59531000000, 'otherFinancingCashFlows': None, 'reportDate': '2018-11-05', 'symbol': 'AAPL', 'totalInvestingCashFlows': 16066000000, 'id': 'CASH_FLOW', 'key': 'AAPL', 'subkey': 'annual', 'date': 1538179200000, 'updated': 1619798873000}, {'capitalExpenditures': -12795000000, 'cashChange': 7026000000, 'cashFlow': 63598000000, 'cashFlowFinancing': -17347000000, 'changesInInventories': 2723000000, 'changesInReceivables': 6374000000, 'currency': 'USD', 'depreciation': 10157000000, 'dividendsPaid': None, 'exchangeRateEffect': None, 'filingType': '10-K', 'fiscalDate': '2017-09-30', 'fiscalQuarter': 0, 'fiscalYear': 2017, 'investingActivityOther': None, 'investments': None, 'netBorrowings': 27563000000, 'netIncome': 48351000000, 'otherFinancingCashFlows': None, 'reportDate': '2017-11-03', 'symbol': 'AAPL', 'totalInvestingCashFlows': -46446000000, 'id': 'CASH_FLOW', 'key': 'AAPL', 'subkey': 'annual', 'date': 1506729600000, 'updated': 1619798873000}]}

In [18]:
df_cashflow = pd.DataFrame()
df_cashflow = df_cashflow.append(df_nested_list,ignore_index=True)
df_cashflow.head()

,accountsPayable,capitalSurplus,commonStock,currency,currentAssets,currentCash,currentLongTermDebt,filingType,fiscalDate,fiscalQuarter,fiscalYear,goodwill,intangibleAssets,inventory,longTermDebt,longTermInvestments,minorityInterest,netTangibleAssets,otherAssets,otherCurrentAssets,otherCurrentLiabilities,otherLiabilities,propertyPlantEquipment,receivables,reportDate,retainedEarnings,shareholderEquity,shortTermInvestments,symbol,totalAssets,totalCurrentLiabilities,totalLiabilities,treasuryStock,id,key,subkey,date,updated
0,42296000000,None,17352119000,USD,143713000000,90943000000,13769000000,10-K,2020-09-26,0,2020,0,0,4061000000,98667000000,180175000000,0,65339000000,42522000000,11264000000,49327000000,54490000000,36766000000,37445000000,2020-10-30,14966000000,65339000000,11264000000,AAPL,323888000000,105392000000,258549000000,0,BALANCE_SHEET,AAPL,annual,1601078400000,1619798874000
1,46236000000,None,18471336000,USD,162819000000,100557000000,16240000000,10-K,2019-09-28,0,2019,0,0,4106000000,91807000000,175697000000,0,90488000000,32978000000,12352000000,43242000000,50503000000,37378000000,45804000000,2019-10-31,45898000000,90488000000,12352000000,AAPL,338516000000,105718000000,248028000000,0,BALANCE_SHEET,AAPL,annual,1569628800000,1619798874000
2,55888000000,None,19821508000,USD,131339000000,66301000000,20748000000,10-K,2018-09-29,0,2018,0,0,3956000000,93735000000,234386000000,0,107147000000,1983000000,12087000000,40230000000,47551000000,41304000000,48995000000,2018-11-05,70400000000,107147000000,12087000000,AAPL,365725000000,116866000000,258578000000,0,BALANCE_SHEET,AAPL,annual,1538179200000,1619798874000
3,49049000000,None,20868968000,USD,128645000000,74181000000,18473000000,10-K,2017-09-30,0,2017,5717000000,2298000000,4855000000,97207000000,246674000000,0,126032000000,10162000000,13936000000,33292000000,11747000000,33783000000,35673000000,2017-11-03,98330000000,134047000000,13936000000,AAPL,375319000000,100814000000,241272000000,0,BALANCE_SHEET,AAPL,annual,1506729600000,1619798874000

In [ ]:
# df_bal_sheet.to_pickle('df_bal_sheet.pickle')

In [ ]:
# stock = IEXStock(config.IEX_TOKEN, 'MSFT')
# print(stock)

In [17]:
cash_flow = stock.get_cash_flow(last=4)

print(cash_flow)

{'symbol': 'MSFT', 'cashflow': [{'capitalExpenditures': -20956679976, 'cashChange': -6277302170, 'cashFlow': 77901719576, 'cashFlowFinancing': -48593028501, 'changesInInventories': 745094375, 'changesInReceivables': 6136028434, 'currency': 'USD', 'depreciation': 11787912519, 'dividendsPaid': None, 'exchangeRateEffect': None, 'filingType': '10-K', 'fiscalDate': '2021-06-25', 'fiscalQuarter': 0, 'fiscalYear': 2039, 'investingActivityOther': None, 'investments': None, 'netBorrowings': -86586077992, 'netIncome': 63035240073, 'otherFinancingCashFlows': None, 'reportDate': '2021-07-23', 'symbol': 'MSFT', 'totalInvestingCashFlows': -27977697136, 'id': 'AOHFCSW_L', 'key': 'TSMF', 'subkey': 'annual', 'date': 1625011200000, 'updated': 1668626399956}, {'capitalExpenditures': -15634150183, 'cashChange': 2778097837, 'cashFlow': 60769572422, 'cashFlowFinancing': -47157177525, 'changesInInventories': -171022686, 'changesInReceivables': 2584439158, 'currency': 'USD', 'depreciation': 12899058280, 'dividendsPaid': None, 'exchangeRateEffect': None, 'filingType': '10-K', 'fiscalDate': '2020-06-22', 'fiscalQuarter': 0, 'fiscalYear': 2106, 'investingActivityOther': None, 'investments': None, 'netBorrowings': -88476780698, 'netIncome': 46344046481, 'otherFinancingCashFlows': None, 'reportDate': '2020-07-20', 'symbol': 'MSFT', 'totalInvestingCashFlows': -12325111554, 'id': 'H_ACSLFWO', 'key': 'MTFS', 'subkey': 'annual', 'date': 1593475200000, 'updated': 1693929766597}, {'capitalExpenditures': -14345493832, 'cashChange': 52669221, 'cashFlow': 54487382966, 'cashFlowFinancing': -38389282520, 'changesInInventories': -618569630, 'changesInReceivables': 3044835815, 'currency': 'USD', 'depreciation': 11770734674, 'dividendsPaid': None, 'exchangeRateEffect': None, 'filingType': '10-K', 'fiscalDate': '2019-06-19', 'fiscalQuarter': 0, 'fiscalYear': 2025, 'investingActivityOther': None, 'investments': None, 'netBorrowings': -75301387363, 'netIncome': 40718548985, 'otherFinancingCashFlows': None, 'reportDate': '2019-07-19', 'symbol': 'MSFT', 'totalInvestingCashFlows': -16180890956, 'id': 'AWS_COHLF', 'key': 'TMFS', 'subkey': 'annual', 'date': 1561852800000, 'updated': 1643259271512}, {'capitalExpenditures': -12057499473, 'cashChange': 787947629, 'cashFlow': 44110310213, 'cashFlowFinancing': -33977645965, 'changesInInventories': 487618343, 'changesInReceivables': 6872350595, 'currency': 'USD', 'depreciation': 10670982009, 'dividendsPaid': None, 'exchangeRateEffect': None, 'filingType': '10-K', 'fiscalDate': '2018-06-27', 'fiscalQuarter': 0, 'fiscalYear': 2075, 'investingActivityOther': None, 'investments': None, 'netBorrowings': -65378710980, 'netIncome': 16677443664, 'otherFinancingCashFlows': None, 'reportDate': '2018-07-24', 'symbol': 'MSFT', 'totalInvestingCashFlows': -6355239189, 'id': 'COASWFH_L', 'key': 'MSTF', 'subkey': 'annual', 'date': 1530316800000, 'updated': 1680170673228}]}

In [21]:
# Flatten data
df_nested_list = pd.json_normalize(cash_flow, record_path =['cashflow'])
df_nested_list

,capitalExpenditures,cashChange,cashFlow,cashFlowFinancing,changesInInventories,changesInReceivables,currency,depreciation,dividendsPaid,exchangeRateEffect,filingType,fiscalDate,fiscalQuarter,fiscalYear,investingActivityOther,investments,netBorrowings,netIncome,otherFinancingCashFlows,reportDate,symbol,totalInvestingCashFlows,id,key,subkey,date,updated
0,-7309000000,-9614000000,80674000000,-86820000000,-45000000,-8359000000,USD,11056000000,None,None,10-K,2020-09-26,0,2020,None,None,10229000000,57411000000,None,2020-10-30,AAPL,-4289000000,CASH_FLOW,AAPL,annual,1601078400000,1619798873000
1,-10495000000,34256000000,69391000000,-90976000000,150000000,-3191000000,USD,12547000000,None,None,10-K,2019-09-28,0,2019,None,None,-4862000000,55256000000,None,2019-10-31,AAPL,45896000000,CASH_FLOW,AAPL,annual,1569628800000,1619798873000
2,-13313000000,-7880000000,77434000000,-87876000000,-899000000,13322000000,USD,10903000000,None,None,10-K,2018-09-29,0,2018,None,None,36095000000,59531000000,None,2018-11-05,AAPL,16066000000,CASH_FLOW,AAPL,annual,1538179200000,1619798873000
3,-12795000000,7026000000,63598000000,-17347000000,2723000000,6374000000,USD,10157000000,None,None,10-K,2017-09-30,0,2017,None,None,27563000000,48351000000,None,2017-11-03,AAPL,-46446000000,CASH_FLOW,AAPL,annual,1506729600000,1619798873000

In [22]:
df_nested_list.to_excel('cash_flow_aapl.xlsx')

In [ ]:
# df_cash_flow = pd.DataFrame()

In [ ]:
df_income = pd.DataFrame()

In [ ]:
df_cash_flow = df_cash_flow.append(df_nested_list,ignore_index=True)
df_cash_flow.head()

In [ ]:
df_cash_flow.to_pickle('df_cash_flow.pickle')

In [ ]:
stock = IEXStock(config.IEX_TOKEN, 'EWBC')
print(stock)

In [23]:
income = stock.get_income(last=4)

print(income)

{'symbol': 'AAPL', 'income': [{'costOfRevenue': 169559000000, 'currency': 'USD', 'ebit': 66288000000, 'filingType': '10-K', 'fiscalDate': '2020-09-26', 'fiscalQuarter': 0, 'fiscalYear': 2020, 'grossProfit': 104956000000, 'incomeTax': 9680000000, 'interestIncome': 2873000000, 'minorityInterest': 0, 'netIncome': 57411000000, 'netIncomeBasic': 57411000000, 'operatingExpense': 208227000000, 'operatingIncome': 66288000000, 'otherIncomeExpenseNet': 0, 'pretaxIncome': 67091000000, 'reportDate': '2020-10-30', 'researchAndDevelopment': 18752000000, 'sellingGeneralAndAdmin': 19916000000, 'symbol': 'AAPL', 'totalRevenue': 274515000000, 'id': 'INCOME', 'key': 'AAPL', 'subkey': 'annual', 'date': 1601078400000, 'updated': 1619798874000}, {'costOfRevenue': 161782000000, 'currency': 'USD', 'ebit': 63930000000, 'filingType': '10-K', 'fiscalDate': '2019-09-28', 'fiscalQuarter': 0, 'fiscalYear': 2019, 'grossProfit': 98392000000, 'incomeTax': 10481000000, 'interestIncome': 3576000000, 'minorityInterest': 0, 'netIncome': 55256000000, 'netIncomeBasic': 55256000000, 'operatingExpense': 196244000000, 'operatingIncome': 63930000000, 'otherIncomeExpenseNet': 0, 'pretaxIncome': 65737000000, 'reportDate': '2019-10-31', 'researchAndDevelopment': 16217000000, 'sellingGeneralAndAdmin': 18245000000, 'symbol': 'AAPL', 'totalRevenue': 260174000000, 'id': 'INCOME', 'key': 'AAPL', 'subkey': 'annual', 'date': 1569628800000, 'updated': 1619798874000}, {'costOfRevenue': 163756000000, 'currency': 'USD', 'ebit': 70898000000, 'filingType': '10-K', 'fiscalDate': '2018-09-29', 'fiscalQuarter': 0, 'fiscalYear': 2018, 'grossProfit': 101839000000, 'incomeTax': 13372000000, 'interestIncome': 3240000000, 'minorityInterest': 0, 'netIncome': 59531000000, 'netIncomeBasic': 59531000000, 'operatingExpense': 194697000000, 'operatingIncome': 70898000000, 'otherIncomeExpenseNet': 0, 'pretaxIncome': 72903000000, 'reportDate': '2018-11-05', 'researchAndDevelopment': 14236000000, 'sellingGeneralAndAdmin': 16705000000, 'symbol': 'AAPL', 'totalRevenue': 265595000000, 'id': 'INCOME', 'key': 'AAPL', 'subkey': 'annual', 'date': 1538179200000, 'updated': 1619798874000}, {'costOfRevenue': 141048000000, 'currency': 'USD', 'ebit': 61344000000, 'filingType': '10-K', 'fiscalDate': '2017-09-30', 'fiscalQuarter': 0, 'fiscalYear': 2017, 'grossProfit': 88186000000, 'incomeTax': 15738000000, 'interestIncome': 2323000000, 'minorityInterest': 0, 'netIncome': 48351000000, 'netIncomeBasic': 48351000000, 'operatingExpense': 167890000000, 'operatingIncome': 61344000000, 'otherIncomeExpenseNet': 0, 'pretaxIncome': 64089000000, 'reportDate': '2017-11-03', 'researchAndDevelopment': 11581000000, 'sellingGeneralAndAdmin': 15261000000, 'symbol': 'AAPL', 'totalRevenue': 229234000000, 'id': 'INCOME', 'key': 'AAPL', 'subkey': 'annual', 'date': 1506729600000, 'updated': 1619798874000}]}

In [24]:
# import pandas as pd
df_nested_list = pd.json_normalize(income, record_path =['income'])
df_nested_list

,costOfRevenue,currency,ebit,filingType,fiscalDate,fiscalQuarter,fiscalYear,grossProfit,incomeTax,interestIncome,minorityInterest,netIncome,netIncomeBasic,operatingExpense,operatingIncome,otherIncomeExpenseNet,pretaxIncome,reportDate,researchAndDevelopment,sellingGeneralAndAdmin,symbol,totalRevenue,id,key,subkey,date,updated
0,169559000000,USD,66288000000,10-K,2020-09-26,0,2020,104956000000,9680000000,2873000000,0,57411000000,57411000000,208227000000,66288000000,0,67091000000,2020-10-30,18752000000,19916000000,AAPL,274515000000,INCOME,AAPL,annual,1601078400000,1619798874000
1,161782000000,USD,63930000000,10-K,2019-09-28,0,2019,98392000000,10481000000,3576000000,0,55256000000,55256000000,196244000000,63930000000,0,65737000000,2019-10-31,16217000000,18245000000,AAPL,260174000000,INCOME,AAPL,annual,1569628800000,1619798874000
2,163756000000,USD,70898000000,10-K,2018-09-29,0,2018,101839000000,13372000000,3240000000,0,59531000000,59531000000,194697000000,70898000000,0,72903000000,2018-11-05,14236000000,16705000000,AAPL,265595000000,INCOME,AAPL,annual,1538179200000,1619798874000
3,141048000000,USD,61344000000,10-K,2017-09-30,0,2017,88186000000,15738000000,2323000000,0,48351000000,48351000000,167890000000,61344000000,0,64089000000,2017-11-03,11581000000,15261000000,AAPL,229234000000,INCOME,AAPL,annual,1506729600000,1619798874000

In [25]:
df_nested_list.to_excel('income_aapl.xlsx')

In [ ]:
df_income = df_income.append(df_nested_list,ignore_index=True)
df_income.head()

In [ ]:
df_income

In [ ]:
df_income = df_income.drop([4,5,6,7])

In [ ]:
df_income.to_pickle('df_income.pickle')

In [ ]:
!pip install openpyxl

In [ ]:
df_income.to_excel('df_income.xlsx')

In [ ]:
df_cash_flow = pd.read_pickle('df_cash_flow.pickle')

In [ ]:
df_cash_flow.to_excel('df_cash_flow.xlsx')

In [ ]:
df_balance_sheet = pd.read_pickle('df_bal_sheet.pickle')
df_balance_sheet.to_excel('df_balance_sheet.xlsx')

In [22]:
df_bal_sheet = pd.read_pickle('df_bal_sheet.pickle')
df_bal_sheet

,accountsPayable,capitalSurplus,commonStock,currency,currentAssets,currentCash,currentLongTermDebt,filingType,fiscalDate,fiscalQuarter,fiscalYear,goodwill,intangibleAssets,inventory,longTermDebt,longTermInvestments,minorityInterest,netTangibleAssets,otherAssets,otherCurrentAssets,otherCurrentLiabilities,otherLiabilities,propertyPlantEquipment,receivables,reportDate,retainedEarnings,shareholderEquity,shortTermInvestments,symbol,totalAssets,totalCurrentLiabilities,totalLiabilities,treasuryStock,id,key,subkey,date,updated
0,15163000000,None,7547000000,USD,184406000000,130334000000,8072000000,10-K,2021-06-30,0,2021,49711000000,7800000000,2636000000,50074000000,149373000000,0,84477000000,15075000000,13393000000,65422000000,43233000000,59715000000,38043000000,2021-07-29,57055000000,141988000000,13393000000,MSFT,333779000000,88657000000,191791000000,0,BALANCE_SHEET,MSFT,annual,1625011200000,1627744044000
1,12530000000,None,7610000000,USD,181915000000,136527000000,3749000000,10-K,2020-06-30,0,2020,43351000000,7038000000,1895000000,59578000000,119396000000,0,67915000000,13138000000,11482000000,56031000000,43244000000,44151000000,32011000000,2020-07-31,34566000000,118304000000,11482000000,MSFT,301311000000,72310000000,183007000000,0,BALANCE_SHEET,MSFT,annual,1593475200000,1619798874000
2,9382000000,None,7673000000,USD,175552000000,133819000000,5516000000,10-K,2019-06-30,0,2019,42026000000,7750000000,2063000000,66662000000,111004000000,0,52554000000,14723000000,10146000000,54522000000,41723000000,36477000000,29524000000,2019-08-01,24150000000,102330000000,10146000000,MSFT,286556000000,69420000000,184226000000,0,BALANCE_SHEET,MSFT,annual,1561852800000,1619798874000
3,8617000000,None,7700000000,USD,169662000000,133768000000,3998000000,10-K,2018-06-30,0,2018,35683000000,8053000000,2662000000,72242000000,89186000000,0,38982000000,7442000000,6751000000,45873000000,39291000000,29460000000,26481000000,2018-08-03,13682000000,82718000000,6751000000,MSFT,258848000000,58488000000,176130000000,0,BALANCE_SHEET,MSFT,annual,1530316800000,1619798874000
4,836000000,None,402000000,USD,11895000000,7618000000,827000000,10-K,2020-11-01,0,2020,43447000000,16782000000,1003000000,40235000000,64038000000,0,-36355000000,1300000000,977000000,4708000000,5426000000,2509000000,2297000000,2020-12-18,0,23901000000,977000000,AVGO,75933000000,6371000000,52032000000,0,BALANCE_SHEET,AVGO,annual,1604188800000,1619798874000
5,855000000,None,398000000,USD,9917000000,5055000000,2787000000,10-K,2019-11-03,0,2019,36714000000,17554000000,874000000,30011000000,57576000000,0,-29327000000,743000000,729000000,3257000000,5613000000,2565000000,3259000000,2019-12-20,0,24970000000,729000000,AVGO,67493000000,6899000000,42523000000,0,BALANCE_SHEET,AVGO,annual,1572739200000,1619798874000
6,811000000,None,418000000,USD,9107000000,4292000000,0,10-K,2018-11-04,0,2018,26913000000,10762000000,1124000000,17493000000,41017000000,0,-11018000000,707000000,301000000,1527000000,3467000000,2635000000,3390000000,2018-12-21,3487000000,26657000000,301000000,AVGO,50124000000,2338000000,23467000000,0,BALANCE_SHEET,AVGO,annual,1541289600000,1619798874000
7,1105000000,None,405000000,USD,15823000000,11204000000,117000000,10-K,2017-10-29,0,2017,24706000000,10832000000,1447000000,17431000000,38595000000,2901000000,-15253000000,458000000,724000000,1307000000,1253000000,2599000000,2448000000,2017-12-21,-129000000,20285000000,724000000,AVGO,54418000000,2529000000,34133000000,0,BALANCE_SHEET,AVGO,annual,1509235200000,1619798874000
8,475500000,None,107600000,USD,9779100000,3587000000,0,10-K,2020-12-31,0,2020,0,0,1916600000,2695700000,7384200000,0,11025300000,168100000,160800000,2221900000,744900000,3221600000,4114700000,2021-02-08,10893000000,11025300000,160800000,REGN,17163300000,2697400000,6138000000,-6613300000,BALANCE_SHEET,REGN,annual,1609372800000,1619798874000
9,418100000,None,109200000,USD,7689100000,3214300000,0,10-K,2019-12-31,0,2019,0,0,1415500000,713900000,7116100000,0,11089700000,144700000,387100000,1678500000,905000000,2890400000,2672200000,2020-02-07,7379800000,11089700000,387100000,REGN,14805200000,2096600000,3715500000,-739900000,BALANCE_SHEET,REGN,annual,1577750400000,1619798874000
10,218200000,None,107900000,USD,6447600000,2809900000,0,10-K,2018-12-31,0,2018,0,0,1151200000,708500000,5286900000,0,8757300000,127400000,243300000,1224600000,825900000,2575800000,2243200000,2019-02-07,5254300000,8757300000,243300000,REGN,11734500000,1442800000,2977200000,-396400000,BALANCE_SHEET,REGN,annual,1546214400000,1619798874000
11,178183000,None,106338000,USD,4335030000,1409580000,0,10-K,2017-12-31,0,2017,0,0,726138000,703453000,4429256000,0,6144078000,77866000,224972000,957300000,781272000,2358605000,1974340000,2018-02-08,2946733000,6144078000,224972000,REGN,8764286000,1135483000,2620208000,-316240000,BALANCE_SHEET,REGN,annual,1514678400000,1619798874000
12,0,None,142336000,USD,50168243000,0,820997000,10-K,2020-12-31,0,2020,465697000,0,0,4363000,1988670000,0,4803478000,1324262000,0,45959548000,0,103251000,0,2021-02-26,4000414000,5269175000,8379300000,EWBC,52156913000,46780545000,46887738000,-634083000,BALANCE_SHEET,EWBC,annual,1609372800000,1619798874000
13,0,None,145497000,USD,42594967000,0,926854000,10-K,2019-12-31,0,2019,465697000,0,0,0,1601129000,0,4551920000,917095000,0,38143542000,0,118364000,0,2020-02-27,3689377000,5017617000,4913566000,EWBC,44196096000,39070396000,39178479000,-479864000,BALANCE_SHEET,EWBC,annual,1577750400000,1619798874000
14,0,None,144862000,USD,39713943000,0,530645000,10-K,2018-12-31,0,2018,465547000,0,0,0,1328413000,0,3958427000,743686000,0,36087737000,0,119180000,0,2019-02-27,3160132000,4423974000,4638699000,EWBC,41042356000,36618382000,36618382000,-467961000,BALANCE_SHEET,EWBC,annual,1546214400000,1619798874000
15,0,None,144444000,USD,35789337000,0,495468000,10-K,2017-12-31,0,2017,469433000,0,0,0,1360912000,0,3372518000,678952000,0,32207719000,0,121209000,0,2018-02-27,2576302000,3841951000,4926155000,EWBC,37150249000,32703187000,33308298000,-452327000,BALANCE_SHEET,EWBC,annual,1514678400000,1619798874000

In [23]:
df_bal_sheet['totalRevenue']

KeyError: 'totalRevenue'

In [24]:
df_cash_flow = pd.read_pickle('df_cash_flow.pickle')
df_cash_flow

,capitalExpenditures,cashChange,cashFlow,cashFlowFinancing,changesInInventories,changesInReceivables,currency,depreciation,dividendsPaid,exchangeRateEffect,filingType,fiscalDate,fiscalQuarter,fiscalYear,investingActivityOther,investments,netBorrowings,netIncome,otherFinancingCashFlows,reportDate,symbol,totalInvestingCashFlows,id,key,subkey,date,updated
0,-20622000000,-6193000000,76740000000,-48486000000,741000000,6032000000,USD,11686000000,None,None,10-K,2021-06-30,0,2021,None,None,-85581000000,61271000000,None,2021-07-29,MSFT,-27577000000,CASH_FLOW,MSFT,annual,1625011200000,1627744044000
1,-15441000000,2708000000,60675000000,-46031000000,-168000000,2487000000,USD,12796000000,None,None,10-K,2020-06-30,0,2020,None,None,-84682000000,44281000000,None,2020-07-31,MSFT,-12223000000,CASH_FLOW,MSFT,annual,1593475200000,1619798873000
2,-13925000000,51000000,52185000000,-36887000000,-599000000,3043000000,USD,11682000000,None,None,10-K,2019-06-30,0,2019,None,None,-71787000000,39240000000,None,2019-08-01,MSFT,-15773000000,CASH_FLOW,MSFT,annual,1561852800000,1619798873000
3,-11632000000,787000000,43884000000,-33590000000,481000000,6689000000,USD,10261000000,None,None,10-K,2018-06-30,0,2018,None,None,-64279000000,16571000000,None,2018-08-03,MSFT,-6061000000,CASH_FLOW,MSFT,annual,1530316800000,1619798873000
4,-463000000,2563000000,12061000000,1611000000,129000000,-962000000,USD,6905000000,None,None,10-K,2020-11-01,0,2020,None,None,32467000000,2663000000,None,2020-12-18,AVGO,-11109000000,CASH_FLOW,AVGO,annual,1604188800000,1619798873000
5,-432000000,763000000,9697000000,6488000000,-250000000,-131000000,USD,5808000000,None,None,10-K,2019-11-03,0,2019,None,None,27014000000,2695000000,None,2019-12-20,AVGO,-15422000000,CASH_FLOW,AVGO,annual,1572739200000,1619798873000
6,-635000000,-6912000000,8880000000,-11118000000,-323000000,942000000,USD,4081000000,None,None,10-K,2018-11-04,0,2018,None,None,12900000000,12259000000,None,2018-12-21,AVGO,-4674000000,CASH_FLOW,AVGO,annual,1541289600000,1619798873000
7,-1069000000,8107000000,6551000000,2230000000,47000000,267000000,USD,4737000000,None,None,10-K,2017-10-29,0,2017,None,None,5620000000,1692000000,None,2017-12-21,AVGO,-674000000,CASH_FLOW,AVGO,annual,1509235200000,1619798873000
8,-614600000,372700000,2618100000,-1970500000,501100000,1442500000,USD,235900000,None,None,10-K,2020-12-31,0,2020,None,None,-1052100000,3513200000,None,2021-02-08,REGN,-70600000,CASH_FLOW,REGN,annual,1609372800000,1619798873000
9,-429600000,404400000,2430000000,-252100000,264300000,429000000,USD,210300000,None,None,10-K,2019-12-31,0,2019,None,None,-2887500000,2115800000,None,2020-02-07,REGN,-2027800000,CASH_FLOW,REGN,annual,1577750400000,1619798873000
10,-383100000,1400320000,2195100000,-77100000,425062000,268860000,USD,148200000,None,None,10-K,2018-12-31,0,2018,None,None,-2344700000,2444400000,None,2019-02-07,REGN,-1463000000,CASH_FLOW,REGN,annual,1546214400000,1619798873000
11,-272626000,370896000,1307112000,-24400000,326782000,362720000,USD,145467000,None,None,10-K,2017-12-31,0,2017,None,None,-931099000,1198511000,None,2018-02-08,REGN,-1005182000,CASH_FLOW,REGN,annual,1514678400000,1619798873000
12,-2656000,756822000,693325000,6908793000,0,0,USD,119908000,None,None,10-K,2020-12-31,0,2020,None,None,-45324912000,567797000,None,2021-02-26,EWBC,-6848716000,CASH_FLOW,EWBC,annual,1609372800000,1619798873000
13,-9859000,259772000,735829000,2124962000,0,0,USD,144178000,None,None,10-K,2019-12-31,0,2019,None,None,-38406964000,674035000,None,2020-02-27,EWBC,-2571176000,CASH_FLOW,EWBC,annual,1577750400000,1619798873000
14,-13787000,826785000,883172000,3800808000,0,0,USD,139499000,None,None,10-K,2018-12-31,0,2018,None,None,-36181921000,703701000,None,2019-02-27,EWBC,-3832412000,CASH_FLOW,EWBC,annual,1546214400000,1619798873000
15,-13754000,296089000,696906000,2068460000,0,0,USD,149822000,None,None,10-K,2017-12-31,0,2017,None,None,-33119277000,505624000,None,2018-02-27,EWBC,-2500455000,CASH_FLOW,EWBC,annual,1514678400000,1619798873000

In [25]:
df_cash_flow.columns

Index(['capitalExpenditures', 'cashChange', 'cashFlow', 'cashFlowFinancing',
       'changesInInventories', 'changesInReceivables', 'currency',
       'depreciation', 'dividendsPaid', 'exchangeRateEffect', 'filingType',
       'fiscalDate', 'fiscalQuarter', 'fiscalYear', 'investingActivityOther',
       'investments', 'netBorrowings', 'netIncome', 'otherFinancingCashFlows',
       'reportDate', 'symbol', 'totalInvestingCashFlows', 'id', 'key',
       'subkey', 'date', 'updated'],
      dtype='object')

In [26]:
df_bal_sheet.columns

Index(['accountsPayable', 'capitalSurplus', 'commonStock', 'currency',
       'currentAssets', 'currentCash', 'currentLongTermDebt', 'filingType',
       'fiscalDate', 'fiscalQuarter', 'fiscalYear', 'goodwill',
       'intangibleAssets', 'inventory', 'longTermDebt', 'longTermInvestments',
       'minorityInterest', 'netTangibleAssets', 'otherAssets',
       'otherCurrentAssets', 'otherCurrentLiabilities', 'otherLiabilities',
       'propertyPlantEquipment', 'receivables', 'reportDate',
       'retainedEarnings', 'shareholderEquity', 'shortTermInvestments',
       'symbol', 'totalAssets', 'totalCurrentLiabilities', 'totalLiabilities',
       'treasuryStock', 'id', 'key', 'subkey', 'date', 'updated'],
      dtype='object')

In [27]:
df_income = pd.read_pickle('./df_income.pickle')
df_income

,costOfRevenue,currency,ebit,filingType,fiscalDate,fiscalQuarter,fiscalYear,grossProfit,incomeTax,interestIncome,minorityInterest,netIncome,netIncomeBasic,operatingExpense,operatingIncome,otherIncomeExpenseNet,pretaxIncome,reportDate,researchAndDevelopment,sellingGeneralAndAdmin,symbol,totalRevenue,id,key,subkey,date,updated
0,52232000000,USD,69916000000,10-K,2021-06-30,0,2021,115856000000,9831000000,2346000000,0,61271000000,61271000000,98172000000,69916000000,0,71102000000,2021-07-29,20716000000,25224000000,MSFT,168088000000,INCOME,MSFT,annual,1625011200000,1627744044000
1,46078000000,USD,52959000000,10-K,2020-06-30,0,2020,96937000000,8755000000,2591000000,0,44281000000,44281000000,90056000000,52959000000,0,53036000000,2020-07-31,19269000000,24709000000,MSFT,143015000000,INCOME,MSFT,annual,1593475200000,1619798874000
2,42910000000,USD,42959000000,10-K,2019-06-30,0,2019,82933000000,4448000000,2686000000,0,39240000000,39240000000,82884000000,42959000000,0,43688000000,2019-08-01,16876000000,23098000000,MSFT,125843000000,INCOME,MSFT,annual,1561852800000,1619798874000
3,38353000000,USD,35058000000,10-K,2018-06-30,0,2018,72007000000,19903000000,2733000000,0,16571000000,16571000000,75302000000,35058000000,0,36474000000,2018-08-03,14726000000,22223000000,MSFT,110360000000,INCOME,MSFT,annual,1530316800000,1619798874000
8,6518000000,USD,4247000000,10-K,2020-11-01,0,2020,17370000000,-518000000,1724000000,0,2663000000,2663000000,19641000000,4247000000,0,2443000000,2020-12-18,4968000000,1935000000,AVGO,23888000000,INCOME,AVGO,annual,1604188800000,1619798874000
9,6723000000,USD,4257000000,10-K,2019-11-03,0,2019,15874000000,-510000000,1346000000,0,2695000000,2695000000,18340000000,4257000000,0,2226000000,2019-12-20,4696000000,1709000000,AVGO,22597000000,INCOME,AVGO,annual,1572739200000,1619798874000
10,7021000000,USD,5458000000,10-K,2018-11-04,0,2018,13827000000,-8084000000,514000000,351000000,12259000000,12259000000,15390000000,5458000000,0,4545000000,2018-12-21,3768000000,1056000000,AVGO,20848000000,INCOME,AVGO,annual,1541289600000,1619798874000
11,6593000000,USD,2689000000,10-K,2017-10-29,0,2017,11043000000,35000000,410000000,92000000,1692000000,1692000000,14947000000,2689000000,0,1825000000,2017-12-21,3292000000,787000000,AVGO,17636000000,INCOME,AVGO,annual,1509235200000,1619798874000
12,491900000,USD,3296200000,10-K,2020-12-31,0,2020,8005200000,297200000,56900000,0,3513200000,3513200000,5200900000,3296200000,0,3810400000,2021-02-08,2735000000,1346000000,REGN,8497100000,INCOME,REGN,annual,1609372800000,1619798874000
13,362300000,USD,2209800000,10-K,2019-12-31,0,2019,7501100000,313300000,30200000,0,2115800000,2115800000,5653600000,2209800000,0,2429100000,2020-02-07,3036600000,1834800000,REGN,7863400000,INCOME,REGN,annual,1577750400000,1619798874000
14,180000000,USD,2534400000,10-K,2018-12-31,0,2018,6530800000,109100000,28200000,0,2444400000,2444400000,4176400000,2534400000,0,2553500000,2019-02-07,2186100000,1556200000,REGN,6710800000,INCOME,REGN,annual,1546214400000,1619798874000
15,202507000,USD,2079591000,10-K,2017-12-31,0,2017,5669720000,880000000,25119000,0,1198511000,1198511000,3792636000,2079591000,0,2078511000,2018-02-08,2075142000,1320433000,REGN,5872227000,INCOME,REGN,annual,1514678400000,1619798874000
16,210653000,USD,685765000,10-K,2020-12-31,0,2020,1619936000,117968000,0,0,567797000,567797000,1144824000,685765000,0,685765000,2021-02-26,0,66489000,EWBC,1830589000,INCOME,EWBC,annual,1609372800000,1619798874000
17,98685000,USD,843803000,10-K,2019-12-31,0,2019,1992878000,169882000,0,0,674035000,674035000,1247760000,843803000,0,843917000,2020-02-27,0,69730000,EWBC,2091563000,INCOME,EWBC,annual,1577750400000,1619798874000
18,64255000,USD,780543000,10-K,2018-12-31,0,2018,1760204000,114995000,0,0,703701000,703701000,1043916000,780543000,0,818696000,2019-02-27,0,68896000,EWBC,1824459000,INCOME,EWBC,annual,1546214400000,1619798874000
19,46266000,USD,653905000,10-K,2017-12-31,0,2017,1456064000,229476000,0,0,505624000,505624000,848425000,653905000,0,735100000,2018-02-27,0,64921000,EWBC,1502330000,INCOME,EWBC,annual,1514678400000,1619798874000

In [28]:
df_income.columns

Index(['costOfRevenue', 'currency', 'ebit', 'filingType', 'fiscalDate',
       'fiscalQuarter', 'fiscalYear', 'grossProfit', 'incomeTax',
       'interestIncome', 'minorityInterest', 'netIncome', 'netIncomeBasic',
       'operatingExpense', 'operatingIncome', 'otherIncomeExpenseNet',
       'pretaxIncome', 'reportDate', 'researchAndDevelopment',
       'sellingGeneralAndAdmin', 'symbol', 'totalRevenue', 'id', 'key',
       'subkey', 'date', 'updated'],
      dtype='object')